// Builds the demo into ONE self-contained HTML file: no server, no CDN, no
// build step at view time. Open `demo/index.html` in a browser.
//
// The source template is `template.html` — it holds placeholders, not a page.
//
// The colour CSS is not hand-written — it is generated by asking the package
// itself what every hue/level resolves to, through the same `paletteShadeHex`
// the XLSX export uses. So the demo cannot drift from the palette it documents.

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  DEFAULT_PALETTE,
  HUES,
  type Hue,
  LEVELS,
  paletteShadeHex,
} from "../src";
import {
  PINNED_EDGE_BORDER,
  PINNED_EDGE_SHADOW,
  PINNED_INNER_EDGE_SHADOW,
} from "../src/layout";

const here = import.meta.dir;
const out = join(here, "index.html");

/** Escape a Tailwind-style class into a valid CSS selector. */
function sel(className: string): string {
  return `.${className.replace(/[^a-zA-Z0-9_-]/g, (ch) => `\\${ch}`)}`;
}

function paletteCss(): string {
  const out: string[] = [
    "/* Generated from the package's own palette — do not edit by hand. */",
  ];
  const shades = [5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100];
  for (const hue of HUES) {
    for (const shade of shades) {
      const hex = paletteShadeHex(hue, shade);
      out.push(`.bg-${hue}-${shade}{background-color:${hex}}`);
      out.push(`.text-${hue}-${shade}{color:${hex}}`);
      out.push(`.border-${hue}-${shade}{border-color:${hex}}`);
    }
  }
  // Sanity: every class the palette map actually names must exist above.
  const named = new Set<string>();
  for (const hue of HUES) {
    for (const level of LEVELS) {
      const s = DEFAULT_PALETTE[hue as Hue][level];
      named.add(s.bg);
      named.add(s.border);
      named.add(s.text);
      named.add(s.inlineText);
    }
  }
  const emitted = new Set(
    out.flatMap((rule) => {
      const m = /^\.([a-z0-9-]+)\{/.exec(rule);
      return m ? [m[1]] : [];
    }),
  );
  const missing = [...named].filter(
    (c) => c !== "text-white" && !emitted.has(c),
  );
  if (missing.length > 0) {
    throw new Error(`palette classes with no CSS rule: ${missing.join(", ")}`);
  }
  return out.join("\n");
}

function engineCss(): string {
  // The three edge treatments come from the package as literal class strings,
  // so the demo styles exactly what the grid asks for.
  const [borderColor, borderSide] = PINNED_EDGE_BORDER.split(" ");
  return `
${sel(borderColor)}{border-color:var(--border)}
${sel(borderSide)}{border-right-width:1px;border-right-style:solid}
${sel(PINNED_EDGE_SHADOW)}{box-shadow:6px 0 8px -4px rgb(0 0 0/0.10)}
${sel(PINNED_INNER_EDGE_SHADOW)}{box-shadow:1px 0 0 var(--bg)}
.px-3{padding-left:.75rem;padding-right:.75rem}
.px-1\\.5{padding-left:.375rem;padding-right:.375rem}
.pl-3\\.5{padding-left:.875rem}
.pr-1\\.5{padding-right:.375rem}
.py-2{padding-top:.5rem;padding-bottom:.5rem}
.align-top{vertical-align:top}
.align-middle{vertical-align:middle}
.whitespace-nowrap{white-space:nowrap}
.whitespace-normal{white-space:normal}
.wrap-break-word{overflow-wrap:break-word}
.overflow-hidden{overflow:hidden}
.text-ellipsis{text-overflow:ellipsis}
.sticky{position:sticky}
.z-10{z-index:10}
.text-left{text-align:left}
.text-center{text-align:center}
.text-right{text-align:right}
.text-white{color:#fff}
.text-muted-foreground{color:var(--muted)}
.text-\\[11px\\]{font-size:11px}
.tabular-nums{font-variant-numeric:tabular-nums}
`.trim();
}

const gridCss = await Bun.file(join(here, "..", "styles", "grid.css")).text();
const chromeCss = await Bun.file(join(here, "demo.css")).text();
const html = await Bun.file(join(here, "template.html")).text();

const built = await Bun.build({
  entrypoints: [join(here, "main.tsx")],
  target: "browser",
  minify: true,
});
if (!built.success) {
  for (const log of built.logs) console.error(log);
  throw new Error("bundle failed");
}
const raw = await built.outputs[0].text();

// Inlining JS into <script> means any literal `</script` in the bundle closes
// the tag early and dumps the rest of the file onto the page as text. React's
// DOM build contains one. Both sequences below can only legally occur inside a
// string, template or regex in valid JS, where the backslash is inert.
const js = raw.replace(/<\/(script)/gi, "<\\/$1").replace(/<!--/g, "<\\!--");

const css = [chromeCss, gridCss, engineCss(), paletteCss()].join("\n\n");
const page = html.replace("/*CSS*/", () => css).replace("//JS", () => js);

await writeFile(out, page);

const kb = (n: number) => `${(n / 1024).toFixed(0)} KB`;
console.log(`demo/index.html  ${kb(page.length)}`);
console.log(`  bundle ${kb(js.length)}   css ${kb(css.length)}`);
